import { defineConfig } from '@playwright/test'

import baseConfig from './playwright.config'

// Deliberately make backend access fail. A test belongs in this suite only when
// every application request and realtime channel it uses is replaced locally.
process.env.VITE_API_PROXY_TARGET = 'http://127.0.0.1:9'
process.env.PLAYWRIGHT_API_URL = 'http://127.0.0.1:9'
process.env.E2E_API_BASE = 'http://127.0.0.1:9'

export default defineConfig({
  ...baseConfig,
  testMatch: [
    '**/agent_chat_resume.spec.ts',
    '**/agent_header.spec.ts',
    '**/agent_ontology_carousel.spec.ts',
    '**/agent_topology_instances.spec.ts',
    '**/assistant_eval.spec.ts',
    '**/assistant_widget.spec.ts',
    '**/asset_lake_tabs.spec.ts',
    '**/community.spec.ts',
    '**/connections_page.spec.ts',
    '**/component_gallery.spec.ts',
    '**/data_mapping_preview.spec.ts',
    '**/event_registry_detail.spec.ts',
    '**/event_registry_edit.spec.ts',
    '**/explore_async_isolation.spec.ts',
    '**/explore_binding_retry.spec.ts',
    '**/explore_diagram_interaction.spec.ts',
    '**/explore_document_risk.spec.ts',
    '**/explore_model_consistency.spec.ts',
    '**/explore_pending_new_session.spec.ts',
    '**/explore_process_panel.spec.ts',
    '**/file_asset_links.spec.ts',
    '**/governance_async_refresh.spec.ts',
    '**/governance_reject_modal.spec.ts',
    '**/governance_story_narrative.spec.ts',
    '**/graph_edge_anchor_routing.spec.ts',
    '**/instance_browser_readonly.spec.ts',
    '**/instance_data_interactions.spec.ts',
    '**/instance_data_overview.spec.ts',
    '**/instance_dataset_navigation.spec.ts',
    '**/integrations_folder_sync.spec.ts',
    '**/mapping_layout_drag.spec.ts',
    '**/mapping_primary_key.spec.ts',
    '**/mapping_review_automation.spec.ts',
    '**/mapping_suggestions.spec.ts',
    '**/login_form_feedback.spec.ts',
    '**/mcp-client-config.spec.ts',
    '**/models.spec.ts',
    '**/nav_tabs.spec.ts',
    '**/ontology_business_model_dialog.spec.ts',
    '**/ontology_card_interactions.spec.ts',
    '**/ontology_domain_source.spec.ts',
    '**/ontology_network_canvas.spec.ts',
    '**/ontology_overview_responsive.spec.ts',
    '**/ontology_structure_doc_dialog.spec.ts',
    '**/ontology_structure_initial_view.spec.ts',
    '**/ontology_runtime_state_conflict.spec.ts',
    '**/ontology_safe_recovery.spec.ts',
    '**/ontology_semantic_gate.spec.ts',
    '**/overview.spec.ts',
    '**/pipeline_list_page.spec.ts',
    '**/profile_modal.spec.ts',
    '**/python_script_page.spec.ts',
    '**/scenes.spec.ts',
    '**/sentinel_firing_delta.spec.ts',
    '**/sentinel_panel_loading.spec.ts',
    '**/settings_monitoring.spec.ts',
    '**/steward_browser_collaboration.spec.ts',
    '**/steward_conversation_export.spec.ts',
    '**/sync_tasks_ui.spec.ts',
    '**/super_assistant_agent_mode.spec.ts',
    '**/super_assistant_evolution.spec.ts',
    '**/super_assistant_workbench.spec.ts',
    '**/theme_toggle.spec.ts',
    '**/tickets.spec.ts',
    '**/trial_action_plan_review.spec.ts',
    '**/world_model.spec.ts',
  ],
  outputDir: '../.artifacts/playwright/mocked-results',
})
